default_configurations =[{  'font'       : 0,
                            'font_size'  : 36,
                            'screen_d'   : 14,
                            'screen_r'   : 16,
                            'wobble'     : 0,
                            'dx'         :0 ,
                            'dy'          :0,
                            'duration'    : 10,
                            'width'      : 300,
                            'height'     : 120,
                            'wordCount'  : 10,
                            'shape'      : 0,
                            'bgColor'    : 255,
                            'bgwColor'   : 100,
                            'screenColor': 155,
                            'fgColor'    : 100 },

                         {  'font'       : 1,
                            'font_size'  : 36,
                            'screen_d'   : 10,
                            'screen_r'   : 16,
                            'wobble'     : 0,
                            'dx'         :0 ,
                            'dy'          :0,
                            'duration'    : 10,
                            'width'      : 300,
                            'height'     : 100,
                            'wordCount'  : 3,
                            'shape'      : 1,
                            'bgColor'    : 255,
                            'bgwColor'   : 0,
                            'screenColor': 0,
                            'fgColor'    : 0 },
                         
                         {  'font'       : 0,
                            'font_size'  : 26,
                            'screen_d'   : 5,
                            'screen_r'   : 10,
                            'wobble'     : 1,
                            'dx'         :1 ,
                            'dy'          :1,
                            'duration'    : 1,
                            'width'      : 200,
                            'height'     : 80,
                            'wordCount'  : 3,
                            'shape'      : 2,
                            'bgColor'    : 255,
                            'bgwColor'   : 00,
                            'screenColor': 00,
                            'fgColor'    : 00 },
                         
             ]
