default_configurations = [

    # 0 — Bradley Hand, ellipse grating, solid fills
    {   'font'       : 0,
        'font_size'  : 36,
        'screen_d'   : 14,
        'screen_r'   : 16,
        'wobble'     : 0,
        'dx'         : 0,
        'dy'         : 0,
        'duration'   : 10,
        'width'      : 300,
        'height'     : 120,
        'wordCount'  : 10,
        'shape'      : 0,
        'bgColor'    : 255,
        'bgwColor'   : 100,
        'screenColor': 155,
        'fgColor'    : 100,
        'texture'    : 0 },

    # 1 — Arial, rectangle grating, solid fills
    {   'font'       : 1,
        'font_size'  : 36,
        'screen_d'   : 10,
        'screen_r'   : 16,
        'wobble'     : 0,
        'dx'         : 0,
        'dy'         : 0,
        'duration'   : 10,
        'width'      : 300,
        'height'     : 100,
        'wordCount'  : 3,
        'shape'      : 1,
        'bgColor'    : 255,
        'bgwColor'   : 0,
        'screenColor': 0,
        'fgColor'    : 0,
        'texture'    : 0 },

    # 2 — Bradley Hand, thin rectangle grating, wobble, solid fills
    {   'font'       : 0,
        'font_size'  : 26,
        'screen_d'   : 5,
        'screen_r'   : 10,
        'wobble'     : 1,
        'dx'         : 1,
        'dy'         : 1,
        'duration'   : 1,
        'width'      : 200,
        'height'     : 80,
        'wordCount'  : 3,
        'shape'      : 2,
        'bgColor'    : 255,
        'bgwColor'   : 0,
        'screenColor': 0,
        'fgColor'    : 0,
        'texture'    : 0 },

    # 3 — white noise textures; each layer's noise moves rigidly with that layer
    #     wobble must stay 0 so noise and mask layers get the same shift each frame
    {   'font'       : 2,    # Arial Black — bold, thick strokes
        'font_size'  : 56,
        'screen_d'   : 12,
        'screen_r'   : 20,
        'wobble'     : 0,
        'dx'         : 1,
        'dy'         : 1,
        'duration'   : 8,
        'width'      : 360,
        'height'     : 150,
        'wordCount'  : 0,    # no background decoy words; noise does the work
        'shape'      : 0,
        'bgColor'    : 128,
        'bgwColor'   : 0,
        'screenColor': 0,
        'fgColor'    : 0,
        'texture'    : 1 },

]
