runtime: python312

handlers:
- url: /images
  static_dir: images
- url: /stylesheets
  static_dir: stylesheets
- url: /favicon.ico
  static_files: favicon.ico
  upload: favicon.ico
- url: /.*
  script: auto
